spring.application.name=${SPRING_APPLICATION_NAME}
server.port=${SERVER_PORT}

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}

# Email Config
email.smtp.host=${EMAIL_SMTP_HOST}
email.smtp.port=${EMAIL_SMTP_PORT}
email.smtp.username=${EMAIL_SMTP_USERNAME}
email.smtp.password=${EMAIL_SMTP_PASSWORD}
email.smtp.auth=${EMAIL_SMTP_AUTH}
email.smtp.starttls=${EMAIL_SMTP_STARTTLS}
email.from.name=${EMAIL_FROM_NAME}
