#spring.application.name=${SPRING_APPLICATION_NAME}
#server.port=${SERVER_PORT}
#
#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=${SPRING_DATASOURCE_DRIVER_CLASS_NAME}
#
#spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO}
#spring.jpa.show-sql=${SPRING_JPA_SHOW_SQL}
#spring.jpa.database-platform=${SPRING_JPA_DATABASE_PLATFORM}
#
## Security
##spring.security.oauth2.resourceserver.jwt.issuer-uri=http://192.168.2.100:8000
##spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://192.168.4.41:8000/.well-known/jwks.json
#
#spring.security.oauth2.resourceserver.jwt.issuer-uri=${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_ISSUER_URI}
#
## Email Config
#email.smtp.host=${EMAIL_SMTP_HOST}
#email.smtp.port=${EMAIL_SMTP_PORT}
#email.smtp.username=${EMAIL_SMTP_USERNAME}
#email.smtp.password=${EMAIL_SMTP_PASSWORD}
#email.smtp.auth=${EMAIL_SMTP_AUTH}
#email.smtp.starttls=${EMAIL_SMTP_STARTTLS}
#email.from.name=${EMAIL_FROM_NAME}


## Application
spring.application.name=employee-leave-management
server.port=9999

# Database
spring.datasource.url=jdbc:mysql://paves-employee-leave-management-sathwikpatel121-0c29.g.aivencloud.com:22824/defaultdb
spring.datasource.username=avnadmin
spring.datasource.password=AVNS_ozMzg2D8Yd5EL8cy7Wh
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

# Security
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://192.168.2.88:8000
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://13.48.18.145
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://192.168.4.41:8000/.well-known/jwks.json

# Alternate Security (Keycloak example)
#spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8000/realms/paves
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8000/realms/paves/protocol/openid-connect/certs

# Email Config (Gmail Example)
email.smtp.host=smtp.gmail.com
email.smtp.port=587
email.smtp.username=pavestechnologies1@gmail.com
email.smtp.password=zyma guto illq zoxy
email.smtp.auth=true
email.smtp.starttls=true
email.from.name=Leave Management System

