package com.paves.employee_leave_management.enums;

public enum ActionType {
    CREATE_LEAVE_TYPE,
    UPDATE_LEAVE_TYPE,
    DEACTIVATE_LEAVE_TYPE,
    UPDATE_EMPLOYEE_LEAVE_BALANCE,
    ADD_HOLIDAY,
    UPDATE_HOLIDAY,
    DELETE_HOLIDAY,
    CREATE_GENDER_BASED_LEAVE,
    UPDATE_GENDER_BASED_LEAVE,
    DEACTIVATE_GENDER_BASED_LEAVE_TYPE;
}
