package com.paves.employee_leave_management.enums;

public enum RuleSetName {
    LEAVE_APPROVAL,
    LEAVE_APPROVAL_CASUAL,
    LEAVE_APPROVAL_SICK,
    LEAVE_APPROVAL_MATERNITY,
    LEAVE_APPROVAL_PATERNITY,
    LEAVE_APPROVAL_COMP_OFF,
    LEAVE_APPROVAL_OPTIONAL_HOLIDAY,
    LEAVE_APPROVAL_LONG_DURATION,
    HR_LEAVE_TYPE_MANAGE,
    HR_LEAVE_BALANCE_ADJUST,
    HR_HOLIDAY_MANAGE,
    HR_WORKFLOW_CONFIG,
    LEAVE_RULE_SIMULATION,
    HR_RULE_SIMULATION,
    DELEGATION_RULE_MANAGEMENT,
    PERMISSION_MANAGEMENT
}
