package com.paves.employee_leave_management.auditRepo;

import com.paves.employee_leave_management.audit_tables.GenderBasedLeaveBalanceAudit;

public interface GenderBasedLeaveBalanceAuditRepo extends BaseAuditRepository<GenderBasedLeaveBalanceAudit>{
}
